CREATE SEQUENCE "HIBERNATE_SEQUENCE" START WITH 1;

CREATE TABLE "BOLTZMANN"(
    "TXID" VARCHAR(255) NOT NULL,
    "DATA" TEXT NOT NULL,
    "EFFICIENCY" DOUBLE NOT NULL,
    "ENTROPY" DOUBLE NOT NULL,
    "NB_CMBN" INTEGER NOT NULL,
    PRIMARY KEY("TXID")
);

CREATE TABLE "LOG"(
    "ID" BIGINT NOT NULL,
    "CREATED" BIGINT NOT NULL,
    "DATA" TEXT,
    "AMOUNT" BIGINT,
    "FROM_ACCOUNT" INTEGER,
    "FROM_ADDRESS" VARCHAR(255),
    "FROM_HASH" VARCHAR(255),
    "FROM_INDEX" INTEGER,
    "LOG_TYPE" INTEGER NOT NULL,
    "TO_ACCOUNT" INTEGER,
    "TO_ADDRESS" VARCHAR(255),
    "TO_HASH" VARCHAR(255),
    "TO_INDEX" INTEGER,
    PRIMARY KEY("ID")
);